config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  controller :pages do
    get :home
    get :application_design
    get :ecommerce
    get :mobile_design
    get :responsive_web
    get :growth_hacking
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def pages
  end
end

app/controllers/pages_controller.rb
class PagesController < ActionController::Base
  layout 'application'

  def home
  end

  def application_design
  end

  def ecommerce
  end

  def mobile_design
  end

  def responsive_web
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def public_url(file)
    root_url + file
  end

  def logo_link
    params[:action] == "home" ? '#top' : home_path
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/layouts/_footer.html.erb
<footer class="border-top-pink footer section-hero-zigzag" id="footer">
  <div class="container footer-container">
    <div class="row footer-container-row">

      <div class="col-xs-12 col-sm-6">
        <h5 class="grey-text text-darken-4">Contact Zach</h5>
        <ul class="row">
          <li class="col-xs-12 col-sm-6"><p class="l-section-close"><%= mail_to 'schweitzdesign@gmail.com', 'Email', title: 'Email schweitzdesign@gmail.com', class: 'link ' %></p></li>

          <li class="col-xs-12 col-sm-6"><p class="l-section-close"><%= link_to 'Twitter', 'https://twitter.com/schweitzdesign', title: 'Zachary Schweitzer on Twitter', class: 'link ' %></p></li>
          <li class="col-xs-12 col-sm-6"><p class="l-section-close"><%= link_to 'LinkedIn', 'https://www.linkedin.com/in/zachary-schweitzer-28037522/', title: 'Zachary Schweitzer on LinkedIn', class: 'link ' %></p></li>
          <li class="col-xs-12 col-sm-6"><p class="l-section-close"><%= link_to 'Instagram', 'https://www.instagram.com/schweitzdesign/', title: 'Zachary Schweitzer on Instagram', class: 'link ' %></p></li>

          <li class="col-xs-12 col-sm-6"><p class="l-section-close"><%= link_to 'Dribbble', 'https://dribbble.com/schweitzdesign', title: 'Zachary Schweitzer on Dribbble', class: 'link ' %></p></li>
          <li class="col-xs-12 col-sm-6"><p class="l-section-close"><%= link_to 'GitHub', 'https://github.com/schweitzdesign', title: 'Zachary Schweitzer on GitHub', class: 'link ' %></p></li>
        </ul>
      </div>


      <div class="col-xs-12 col-sm-6">
        <h5 class="grey-text text-darken-4">Case Studies</h5>
        <ul class='row'>
          <li class="col-xs-12 col-sm-6"><p class="l-section-close"><%= link_to 'Growth Hacking', growth_hacking_path, title: 'Growth Hacking', class: 'link ' %></p></li>
          <li class="col-xs-12 col-sm-6"><p class="l-section-close"><%= link_to 'Application Design', application_design_path, title: 'Application Design', class: 'link ' %></p></li>
          <li class="col-xs-12 col-sm-6"><p class="l-section-close"><%= link_to 'E-Commerce', ecommerce_path, title: 'E-Commerce', class: 'link ' %></p></li>
          <li class="col-xs-12 col-sm-6"><p class="l-section-close"><%= link_to 'Mobile Onboarding', mobile_design_path, title: 'Mobile Onboarding', class: 'link ' %></p></li>
          <li class="col-xs-12 col-sm-6"><p class="l-section-close"><%= link_to 'Responsive Web Design', responsive_web_path, title: 'Responsive Web Design', class: 'link ' %></p></li>
        </ul>
      </div>

      <div class="col-xs-12 center-align">
        <p class="grey-text text-darken-4 footer-attribution_text">Made with <%= link_to 'Materialize', 'http://materializecss.com/', class: 'link ', title: 'Materialize CSS' %>, <%= link_to 'SMACSS', 'https://smacss.com/', class: 'link ', title: 'Scalable and Modular Architecture for CSS' %>, <%= link_to "Flexbox Grid", "http://flexboxgrid.com/", class: 'link ', title: 'Flexbox Grid' %>, Ruby on Rails, Heroku, and Cloudfront. View source on <%= link_to "BitBucket.", "https://bitbucket.org/schweitzdesign/portfolio/overview", class: 'link ', title: 'View Source on BitBucket' %></p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="border-top-green header" id="top">
  <div class="container">
    <div class="col s12 center-align">
      <%= link_to '#', title: 'Zachary Schweitzer Design Portfolio Navigation', :data => { :activates => 'slide-out', :turbolinks => "false"}, class: "button-collapse show-on-large logo valign-wrapper js-logo" do %>&nbsp;<% end %>
    </div>
  </div>

  <ul id="slide-out" class="side-nav section-nav pink lighten-1 center-align valign-wrapper">

    <li class="side-nav-title_item">
      <h1 class='side-nav-title white-text'>the Design Portfolio of Zachary Schweitzer</h1>
    </li>

    <li class="side-nav-link-close">
      <i id="#close-nav" class="material-icons white-text close_nav">close</i>
    </li>

    <li><%= link_to "Home", root_path, :data => { :turbolinks => "false" }, class: "side-nav-link white-text #{'active' if current_page?(root_path)}", title: 'Back to Zach' %></li>
    <li><%= link_to "Growth Hacking", growth_hacking_path, :data => { :turbolinks => "false" }, class: "side-nav-link white-text #{'active' if current_page?(growth_hacking_path)}", title: 'Growth Hacking Case Study' %></li>
    <li><%= link_to "Application Design", application_design_path, :data => { :turbolinks => "false" }, class: "side-nav-link white-text #{'active' if current_page?(application_design_path)}", title: 'Application Design Case Study' %></li>
    <li><%= link_to "E-Commerce",ecommerce_path, :data => { :turbolinks => "false" }, class: "side-nav-link white-text #{'active' if current_page?(ecommerce_path)}", title: 'E-commerce Design Case Study' %></li>
    <li><%= link_to "Mobile Apps", mobile_design_path, :data => { :turbolinks => "false" }, class: "side-nav-link white-text #{'active' if current_page?(mobile_design_path)}", title: 'Mobile App Design' %></li>
    <li><%= link_to "Responsive Web Design", responsive_web_path, :data => { :turbolinks => "false" }, class: "side-nav-link white-text #{'active' if current_page?(responsive_web_path)}", title: 'Responsive Web Design' %></li>
  </ul>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0">

    <!-- Not quite ready for this to be globally accessible, but we still want the appropriate meta data for later -->
    <meta name="robots" content="noindex,nofollow">
    <meta name="google-site-verification" content="8dtzkteIPfgPhUt8Y4ZzSXUP8FR-gAd0pJJwYH_BZpc" />

    <title>Zachary Schweitzer | Pittsburgh Designer | UX, UI, Web Design, Graphic Design, Illustration</title>
    <meta name="description" content="Pittsburgh designer specializing in UX, UI, Web Design, Graphic Design, and Illustration.">
    <meta property="og:type" content="website">
    <meta property="og:site_name" content="Pittsburgh UX, UI, Web Design, Graphic Design, and Illustration.">
    <meta property="og:url" content="http://www.zachschweitzer.com">
    <meta property="og:title" content="Pittsburgh Designer | UX, UI, Web Design, Graphic Design, and Illustration.">
    <meta property="og:description" content="Zachary Schweitzer is a creative designer specializing in UX, UI, Web Design, Graphic Design, and Illustration.">
    <meta property="og:image" content="//zachschweitzer.com/assets/images/zach-schweitzer.jpg">
    <meta property="og:image:type" content="image/jpg">
    <meta property="og:image:width" content="400">
    <meta property="og:image:height" content="400">

    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="@schweitzdesign">
    <meta name="twitter:creator" content="@schweitzdesign">
    <meta name="twitter:title" content="Zachary Schweitzer | Pittsburgh Designer">
    <meta name="twitter:description" content="Zachary Schweitzer is a creative designer specializing in UX, UI, Web Design, Graphic Design, and Illustration.">
    <meta name="twitter:image" content="//zachschweitzer.com/assets/images/zach-schweitzer.jpg">

    <!-- CSS  -->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons|Lato:700,300,300italic,900" rel="stylesheet">

    <%= csrf_meta_tags %>

    <!-- Favicons  https://realfavicongenerator.net/ -->
    <link rel="apple-touch-icon" sizes="180x180" href="/favicons/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicons/favicon-16x16.png">
    <link rel="manifest" href="/favicons/manifest.json">
    <link rel="mask-icon" href="/favicons/safari-pinned-tab.svg" color="#ee4480">
    <meta name="theme-color" content="#ee4480">
  </head>

  <body>
    <%= render partial: 'layouts/header' %>
    <%= yield %>
    <%= render partial: 'layouts/footer' %>

    <script type="text/javascript">
      // set section height synchronously for overall page performance/user experience
      (function() {
        var divs = document.querySelectorAll('.section');

        [].forEach.call(divs, function(div) {
          div.style.minHeight = window.innerHeight * 0.93 + "px"
        });
      })();
    </script>

    <!--  Scripts-->
    <%= javascript_include_tag 'application', async: Rails.env.production? %>
  </body>
</html>

app/views/pages/growth_hacking.html.erb
<main>
  <section class="section section-hero section-hero-zigzag section-hero-zigzag-alt2 valign-wrapper">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-md-6 col-md-offset-3" id="growth_hacking_intro">
          <p class="pink-text text-lighten-1 center-align">Growth Hacking</p>
          <h2 class="title grey-text text-darken-3 center-align">Accelerating Business Growth with Rapid-Fire Product Design</h2>
          <p class="flow-text grey-text text-darken-2 center-align">As VP of Design & Engineering I led the strategy development, design, and execution of an aggressive product roadmap focused on transformative business growth at Forever.com.</p>

          <p class="center-align"><%= link_to "Tell a Friend", 'https://www.forever.com/referrals', class: "btn-large waves-effect waves-light pink lighten-1", title: "Visit Forever.com" %></p>
        </div>
      </div>
    </div>
  </section>

  <section class="section-highlight light-green lighten-5">
    <div class="container">
      <div class="row">

        <div class="col-xs-12 col-md-6">
          <h5 class="pink-text text-lighten-1">Project Goals</h4>
          <ul class="browser-default list grey-text text-darken-1">
            <li><p class="list-content grey-text text-darken-3">Deepen engagement of current users and customers</p></li>
            <li><p class="list-content grey-text text-darken-3">Increase new user sign ups and conversions</p></li>
            <li><p class="list-content grey-text text-darken-3">Launch new products and features at a regular and rapid cadence in tight coordination with marketing, sales, and support</p></li>
          </ul>
        </div>

        <div class="col-xs-12 col-md-6">
          <h5 class="pink-text text-lighten-1">Key Outcomes</h4>
          <ul class="browser-default list grey-text text-darken-1">
            <li><p class="list-content grey-text text-darken-3">100% growth daily active users</p></li>
            <li><p class="list-content grey-text text-darken-3">100% growth new user sign ups</p></li>
            <li><p class="list-content grey-text text-darken-3">13% top line cash sales growth</p></li>
            <li><p class="list-content grey-text text-darken-3">Delivery of critical platform features that support long-term business vision</p></li>
          </ul>
        </div>

      </div>
    </div>
  </section>

  <section class="section-padded">
    <div class="container">

      <div class="row">
        <div class="col-xs-12 col-md-6 center-align">
          <%= image_tag "growth_hacking/growth_hacking_roadmap_whiteboard.png", class: 'responsive-img', alt: 'Growth Hacking Strategy Whiteboards', title: 'Growth Hacking Strategy Whiteboards' %>
        </div>

        <div class="col-xs-12 col-md-6 center-align">
          <%= image_tag "growth_hacking/growth_hacking_roadmap_docs.png", class: 'responsive-img', alt: 'Growth Hacking Strategy Documents', title: 'Growth Hacking Strategy Documents' %>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-12 col-md-6 col-md-offset-3">
          <h4 class="subtitle pink-text text-lighten-1">Strategy</h2>
          <p class="grey-text text-darken-3">Having spent the prior year <%= link_to 're-designing our core photo application', application_design_path, title: "Application Design Case Study", class: 'link' %>, developing our first custom online print offering, and tackling critical infrastructure initiatives, FOREVER's platform was poised for significant growth.</p>

          <p class="grey-text text-darken-3">To inform our product strategy, I led card sorting sessions with our product management, engineering, marketing, and sales teams. From these sessions, I developed a number of internal information design documents to help unify our thinking on our best opportunities to accelerate growth.</p>

          <p class="grey-text text-darken-3">We introduced a regular cadence of stakeholder meetings to ensure we maintained a 'living roadmap' and continually adapted and course corrected as we delivered and learned from each initiative. Some of the key deliverables included:</p>
        </div>

        <div class="col-xs-12 col-md-8 col-md-offset-2">
          <ul class="browser-default list grey-text text-darken-1 row">
            <li class="col-xs-12 col-sm-6"><p class="list-content"><%= link_to 'Premium Streaming Video', 'https://www.forever.com/video', title: 'FOREVER Premium Video Plan', class: 'link' %></p></li>

            <li class="col-xs-12 col-sm-6"><p class="list-content"><%= link_to 'FOREVER Club Loyalty Program', 'https://www.forever.com/forever_club', title: 'FOREVER Club Loyalty Program', class: 'link' %></p></li>

            <li class="col-xs-12 col-sm-6"><p class="list-content"><%= link_to 'Customer Referrals', 'https://www.forever.com/app/referrals', title: 'Refer A Friend', class: 'link' %></p></li>

            <li class="col-xs-12 col-sm-6"><p class="list-content"><%= link_to 'New Print Products', 'https://www.forever.com/print', title: 'Calendars, Cards, Canvases, and Photo Books', class: 'link' %></p></li>

            <li class="col-xs-12 col-sm-6"><p class="list-content"><%= link_to 'Events Promotion & Ticketing', 'https://www.forever.com/events', title: 'Search FOREVER Public Photos and Albums', class: 'link' %></p></li>

            <li class="col-xs-12 col-sm-6"><p class="list-content"><%= link_to 'Gift Certificate Redesign', 'https://www.forever.com/gifts', title: 'FOREVER Gift Certificates', class: 'link' %></p></li>


            <li class="col-xs-12 col-sm-6"><p class="list-content"><%= link_to 'Public Directory & Search', 'https://www.forever.com/app/account-search', title: 'Search FOREVER Public Photos and Albums', class: 'link' %></p></li>

            <li class="col-xs-12 col-sm-6"><p class="list-content"><%= link_to 'Collaborative Albums', 'https://blog.forever.com/forever-blog/collaborative-albums-launch', title: 'FOREVER Collaborative Albums', class: 'link' %></p></li>
          </ul>
        </div>

        <div class="col-xs-12 col-md-6 col-md-offset-3">
          <p class="list-content grey-text text-darken-3">Additionally, we delivered SEO and performance improvements, a redesigned primary navigation, improvements to the sign up workflow, early renewals and other subscription management features, and <em>many</em> more user experience, resiliency, and engagement features and hacks.</p>
        </div>

      </div>
    </div>
  </section>

  <section class="section-highlight">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 center-align">
          <%= image_tag "growth_hacking/forever-print-app-marketing.png", class: 'responsive-img', alt: 'FOREVER Print Custom Photo Project App Marketing Designs', title: 'FOREVER Print Custom Photo Project App Marketing Designs' %>

          <p class="grey-text text-darken-3 center-align small"><em>FOREVER Print Marketing Designs - Canvases, Cards, and Calendars</em></p>
        </div>
      </div>
    </div>
  </section>

  <section class="section-padded">
    <div class="container">

      <div class="row">
        <div class="col-xs-12 col-md-6 col-md-offset-3">
          <h4 class="subtitle light-green-text">A Design-led Approach</h2>
          <p class="grey-text text-darken-3">At the forefront of nearly every initiatve launched was a designer working our established process by conducting competitor and user research, aligning with business stakeholders, and coordinating with engineers to establish the possibilities, constraints, and goals of any given initiative.
          </p>

          <p class="grey-text text-darken-3">Further, we had a perpetual voice of the customer aiding in our understanding of user contexts by way of a number of learning and feedback tools. We captured and shared <%= link_to 'Zendesk', 'https://www.zendesk.com/', title: 'Zendesk Customer Support', class: 'link', target: '_blank' %> tickets daily, used <%= link_to 'Satismeter', 'https://www.satismeter.com/', title: 'Satismeter Net Promotion Tool', class: 'link', target: '_blank' %> to capture NPS scores and suggestions, participated in a number of private user Facebook groups, and conducted monthly video conferences and calls with our sales team; all in addition to regularly conducting moderated and unmoderated usability testing as well as stakeholder and customer interviews and workshops.
          </p>
        </div>
      </div>
    </div>
  </section>

  <section class="section-highlight">
    <div class="row">
      <div class="col-xs-12 col-md-6 center-align">
        <%= image_tag "growth_hacking/collaboration-research.png", class: 'responsive-img', alt: 'FOREVER Collaborative Albums Research', title: 'FOREVER Collaborative Albums Research' %>
      </div>

      <div class="col-xs-12 col-md-6 center-align">
        <%= image_tag "growth_hacking/collaboration-concepts.png", class: 'responsive-img', alt: 'FOREVER Collaborative Albums Comps and Wireframes', title: 'FOREVER Collaborative Albums Comps and Wireframes' %>
      </div>

      <div class="col-xs-12 center-align">
        <p class="grey-text text-darken-3 center-align small"><em>Collaborative Albums - Research, Artifacts, and Concepts</em></p>
      </div>
    </div>
  </section>

  <section class="section-padded">
    <div class="container">

      <div class="row">
        <div class="col-xs-12 col-md-6 col-md-offset-3">
          <p class="grey-text text-darken-3">By way of both developing a design team that was extremely multi-disciplinary (moving seamlessly from research to front-end code) as well as deeply involving our full cadre of engineers in the business thinking and user context, our team was architected for high-performance execution. We were well-equipped to work at whatever level of fidelity was appropriate to express and then validate a concept and then could ramp up radily into high-fidelity, consumer-grade products and features ready for release.
          </p>
        </div>
      </div>


      <div class="row">
        <div class="col-xs-12 col-md-6 col-md-offset-3">

          <h4 class="subtitle light-green-text">Ideas are Easy. Execution is Everything.</h2>
          <p class="grey-text text-darken-3">Taking extreme heed of the words of John Doerr, we had built and battle-tested an extremely high-performing design and engineering team. Having put our results and learnings from the previous year under the microscope, we recognized a major opportunity to not only deliver robust, performant, and elegantly simple product features, but to deliver these in the tightest possible concert with all other support, marketing, sales, events, and other business goings-on. We worked hard on aligning our product and business roadmap by instituting a much more frequent cadence of cross-functional check-ins, ensuring we had business owners deeply involved in the spec and testing of features within their primary scope, and continually pushed to prioritize key releases against other "running the business" activities that might have otherwise interrupted the high number of coordinated and successful launches we were able to deliver.</p>

          <p><%= link_to "Join Our Club", 'https://www.forever.com/club', class: "btn-large waves-effect waves-light pink lighten-1", title: "FOREVER Club Loyalty and Rewards Program" %></p>
        </div>
      </div>
    </div>
  </section>

  <div class="border-top-pink section-padded">
    <div class="row">
      <div class="col-xs-12 center-align">
        <h4 class="subtitle grey-text text-darken-4">Gallery</h2>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 col-md-6 center-align">
        <%= image_tag "growth_hacking/forever-club-loyalty-program.png", class: 'responsive-img', alt: 'FOREVER Club Loyalty Program Design Artifacts', title: 'FOREVER Club Loyalty Program Design Artifacts' %>
        <p class="grey-text text-darken-3 center-align small"><em>FOREVER Club Loyalty & Rewards Program - Planning Docs, Lo-Fi, and Hi-Fi Comps</em></p>
      </div>

      <div class="col-xs-12 col-md-6 center-align">
        <%= image_tag "growth_hacking/forever-gift-certificates.png", class: 'responsive-img', alt: 'FOREVER Gift Certificates', title: 'FOREVER Gift Certificates' %>
        <p class="grey-text text-darken-3 center-align small"><em>FOREVER Gift Certificates - Refreshed UI, Certificate Design Options, and Bonus Coupon Promotion</em></p>
      </div>

      <div class="col-xs-12 col-md-6 center-align l-section">
        <%= image_tag "growth_hacking/forever-events.png", class: 'responsive-img', alt: 'FOREVER Training and Customer Events', title: 'FOREVER Training and Customer Events' %>
        <p class="grey-text text-darken-3 center-align small"><em>FOREVER Events - New Landing Pages and Ticketing / Ecommerce Functionality</em></p>
      </div>

      <div class="col-xs-12 col-md-6 center-align l-section">
        <%= image_tag "growth_hacking/forever-video.png", class: 'responsive-img', alt: 'FOREVER Premium Streaming Video Plan', title: 'FOREVER Premium Streaming Video Plan' %>
        <p class="grey-text text-darken-3 center-align small"><em>FOREVER Video - Competitor and User Research, Playback States UI, and Pricing</em></p>
      </div>
    </div>

  </div>
</main>

app/views/pages/home.html.erb
<main>
  <section class="section section-hero section-hero-zigzag valign-wrapper">
    <div class="container" id="home_intro">
      <div class="row middle-xs">

        <div class="col-xs-12 col-md-6 center">
          <%= image_tag "zach-schweitzer.png", class: 'responsive-img', alt: 'Zachary Schweitzer, Pittsburgh Designer', title: 'Zachary Schweitzer, Pittsburgh Designer' %>
        </div>

        <div class="col-xs-12 col-md-6 rotate-right">
          <h2 class="title title-home pink-text text-lighten-1">I'm Zach Schweitzer.</h2>
          <p class="flow-text grey-text text-darken-2">I’m a Pittsburgh native, father, dachshund wrangler, and full stack designer seeking compelling opportunities in digital design.</p>

          <%= link_to public_url('zach-schweitzer-2019.pdf'), class: "btn-large pink lighten-1", title: "Download Resume" do %>
             <span class="hide-on-small-only">Get </span>Résumé
          <% end %>
          <%= link_to '#growth_hacking', class: "btn-large light-green lighten-1 js-scroll btn-contact", title: "Contact" do %>
            <i class="material-icons right hide-on-small-only">arrow_downward</i>View Work
          <% end %>
        </div>

      </div>
    </div>
  </section>

  <section class="section section-highlight valign-wrapper">
    <div class="container">
      <div class="row middle-xs" id='growth_hacking'>

        <div class="col-xs-12 col-md-7 center">
          <%= link_to growth_hacking_path, title: 'Growth Hacking Case Study' do %>
            <%= image_tag "home/growth-hacking-design.png", class: 'responsive-img', alt: 'Growth Hacking Designs', title: 'Growth Hacking Designs', :data => { :turbolinks => "false" } %>
          <% end %>
        </div>

        <div class="col-xs-12 col-md-5 rotate-right">
          <h4 class="light-green-text">Growth Hacking</h4>
          <p class="flow-text grey-text text-darken-2">I played a key role in the leadership, design, and execution of Forever's 2018 growth roadmap across web, mobile, ecommerce, marketing, and sales.</p>

          <%= link_to "View Case Study", growth_hacking_path, class: "btn-large pink lighten-1", :data => { :turbolinks => "false" } %>
        </div>

      </div>
    </div>
  </section>

  <section class="section section-hero-zigzag section-hero-zigzag-alt  valign-wrapper">
    <div class="container">
      <div class="row reverse middle-xs" id='application_design'>

        <div class="col-xs-12 col-md-7 center">
          <%= link_to application_design_path, title: 'Application Design Case Study' do %>
            <%= image_tag "home/application-design.png", class: 'responsive-img', alt: 'Application Design', title: 'Application Design', :data => { :turbolinks => "false" } %>
          <% end %>
        </div>

        <div class="col-xs-12 col-md-5 rotate-left">
          <h4 class="pink-text text-lighten-1">Application Design</h4>
          <p class="flow-text grey-text text-darken-2">I led a complete redesign of Forever's core photo organizing application focused on improving usability and performance.</p>

          <%= link_to "View Case Study", application_design_path, class: "btn-large pink lighten-1", :data => { :turbolinks => "false" } %>
        </div>

      </div>
    </div>
  </section>

  <section class="section section-highlight valign-wrapper">
    <div class="container">
      <div class="row middle-xs" id='ecommerce'>

        <div class="col-xs-12 col-md-7 center">
          <%= link_to ecommerce_path, title: 'E-commerce Design Case Study' do %>
            <%= image_tag "home/ecommerce-design.png", class: 'responsive-img', alt: 'E-commerce Design', title: 'E-commerce Design', :data => { :turbolinks => "false" }  %>
          <% end %>
        </div>

        <div class="col-xs-12 col-md-5 rotate-left">
          <h4 class="light-green-text">E-Commerce</h4>
          <p class="flow-text grey-text text-darken-2">I designed Forever's e-commerce platform, from marketing pages and checkout flows to promotions and sales dashboards.</p>

          <%= link_to "View Case Study", ecommerce_path, class: "btn-large pink lighten-1", :data => { :turbolinks => "false" }  %>
        </div>

      </div>
    </div>
  </section>

  <section class="section section-hero-zigzag section-hero-zigzag-alt2 valign-wrapper">
    <div class="container">
      <div class="row reverse middle-xs" id='mobile'>

        <div class="col-xs-12 col-md-7 center">
          <%= link_to mobile_design_path, title: 'Mobile Onboarding Design' do %>
            <%= image_tag "home/mobile-design.png", class: 'responsive-img', alt: 'Mobile Design', title: 'Mobile Design', :data => { :turbolinks => "false" }  %>
          <% end %>
        </div>

        <div class="col-xs-12 col-md-5 rotate-right">
          <h4 class="pink-text text-lighten-1">Mobile App Design</h4>
          <p class="flow-text grey-text text-darken-2">I redesigned the Forever mobile onboarding workflow to improve clarity of options and encourage back up and autosync.</p>

          <%= link_to "View Case Study", mobile_design_path, class: "btn-large pink lighten-1", :data => { :turbolinks => "false" }  %>
        </div>

      </div>
    </div>
  </section>

  <section class="section section-highlight valign-wrapper">
    <div class="container">
      <div class="row middle-xs" id='responsive_web'>

        <div class="col-xs-12 col-md-7 center">
          <%= link_to responsive_web_path, title: 'Responsive Web Design' do %>
            <%= image_tag "home/responsive-web-design.png", class: 'responsive-img', alt: 'Responsive Web', title: 'Responsive Web', :data => { :turbolinks => "false" }  %>
          <% end %>
        </div>

        <div class="col-xs-12 col-md-5 rotate-left">
          <h4 class="light-green-text">Responsive Web Design</h4>
          <p class="flow-text grey-text text-darken-2">At Media Post Inc. I served as project manager, designer, and front-end developer, delivering responsive marketing sites and branded products.</p>

          <%= link_to "View Work", responsive_web_path, class: "btn-large pink lighten-1", :data => { :turbolinks => "false" }  %>
        </div>

      </div>
    </div>
  </section>
</main>